#!/bin/bash

ACTION=$1
if [ -z "$ACTION" ]; then
    ACTION="unknown"
fi
shift
ARGS=$@

# check auth url
if ! [ -z ${OS_AUTH_URL:+x} ]; then
    if [[ $OS_AUTH_URL != *?v3 ]]; then
        OS_AUTH_URL="$OS_AUTH_URL/v3"
    fi
fi

if [ $ACTION == 'mount' ]; then
  cloudfuse $ARGS
elif [ $ACTION == 'unmount' ]; then
  fusermount -u $ARGS
else
  echo "To mount, run 'cc-cloudfuse mount <mount_dir> [options]'; for more about mounting, run 'cc-cloudfuse mount -h'."
  echo "To unmount, run 'cc-cloudfuse unmount <mount_dir>'"
fi