#!/bin/bash

ACTION=$1
if [ -z "$ACTION" ]; then
    ACTION="unknown"
fi
shift
ARGS=$@

OPENSTACK_VENDOR_DATA='http://169.254.169.254/openstack/latest/vendor_data.json'
OPENSTACK_VENDOR_DATA_2='http://169.254.169.254/openstack/latest/vendor_data2.json'

JSON_VENDOR_DATA=$(curl -s $OPENSTACK_VENDOR_DATA_2)
if [ "$JSON_VENDOR_DATA" = '{}' ]; then
  JSON_VENDOR_DATA=$(curl -s $OPENSTACK_VENDOR_DATA)
fi

function extract_json_key {
  RESULT=$(echo "$2" | sed "s/.*$1\": \"//g" | sed 's/".*//g')
  echo "$RESULT"
}

OS_TOKEN=$(extract_json_key "instance_metrics_writer_token" "$JSON_VENDOR_DATA")
OS_PROJECT_ID=$(extract_json_key "project_id" "$JSON_VENDOR_DATA")
OS_AUTH_URL=$(extract_json_key "auth_url_v3" "$JSON_VENDOR_DATA")
OS_REGION=$(extract_json_key "region" "$JSON_VENDOR_DATA")

if [ $ACTION == 'mount' ]; then
  cloudfuse $ARGS
elif [ $ACTION == 'unmount' ]; then
  fusermount -u $ARGS
else
  echo "To mount, run 'cc-cloudfuse mount <mount_dir> [options]'; for more about mounting, run 'cc-cloudfuse mount -h'."
  echo "To unmount, run 'cc-cloudfuse unmount <mount_dir>'"
fi